name: CI

on:
  
  push:
    branch: ["main"]
  
  pull_request:
    branch: ["main"]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Da-da-doo-doot-n, just dance... Spin that record, babe
          echo It's Britney Bitch! And I'm back in a form of a new company.
